version: "3.8"
name: pika
services:
  nginx:
    container_name: pika-nginx
    image: nginx:latest
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/frontend:/web
    ports:
      - "${WEB_EXPOSED_PORT}:80"
    networks:
      internal_net:
    restart: unless-stopped

  python-app:
    container_name: pika-python
    build:
      dockerfile: Dockerfile
    volumes:
      - ./docker/backend:/app
    expose:
      - "8000"
    networks:
      internal_net:
    restart: unless-stopped

networks:
  internal_net:
    driver: bridge